### ISSUE TITLE
关于软件下载链接

### ISSUE THREAD

**Issue by Zeroto521** [JustVita/Excellent-software#1]
对于“下载"，可以提供相应**软件官网**或者是**开发者发布平台**得下载链接吗？

**Comment by JustVita** [comment]
如果能翻墙，软件名也都有，那对于你来讲就是复制粘贴的事情，如果不能翻墙，有些给你链接你也下不了，app同理，有部分开发者并没有上线

**Comment by Zeroto521** [comment]
个人认为与其自己给出链接（鱼）不如提供官网（渔），倒有点这样的意味吧。
或者说这个给出的链接的**安全可靠性**呢？

**Comment by JustVita** [comment]
嗯，你的意见我也赞同，后期我会加上，各种自己可以选择
